kind: Service
apiVersion: v1
metadata:
  name: flask
spec:
  selector:
    svc: flask
  ports:
  - protocol: TCP
    port: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      svc: flask
  replicas: 1
  template:
    metadata:
      labels:
        svc: flask
    spec:


      securityContext:
        fsGroup: 101
      containers:
      - name: flask
        image: sotadb/flask 
        ports: 
        - containerPort: 8080
        volumeMounts:
        - name: flask-cert
          mountPath: "/etc/uwsgi/ssl"
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command: ["install", "-c", "-o", "uwsgi", "-m", "0400", "/etc/uwsgi/ssl/ca.crt", "/etc/uwsgi/ssl/tls.crt", "/etc/uwsgi/ssl/tld.key", "/var/www/ssl"]
      volumes:
      - name: flask-cert
        secret:
          secretName: flask-auth
          defaultMode: 0400
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: flask
spec:
  secretName: flask-auth
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: postgres
  organization:
  - Flask host
  dnsNames:
  - flask
