kind: Service
apiVersion: v1
metadata:
  name: flask
spec:
  selector:
    svc: flask
  ports:
  - protocol: TCP
    port: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      svc: flask
  replicas: 1
  template:
    metadata:
      labels:
        svc: flask
    spec:
      containers:
      - name: flask
        image: sotadb/flask 
        ports: 
        - containerPort: 8080
